frontend: delete RichText tests
Because i could not get them to run with vitest.
The error i could not resolve:
 FAIL  src/components/form/api/__tests__/ApiRichtext.spec.js > An ApiRichtext > updates state if value in store is refreshed and has new value
TypeError: tippy is not a function
 ❯ BubbleMenuView.createTooltip node_modules/@tiptap/extension-bubble-menu/src/bubble-menu-plugin.ts:141:18
 ❯ BubbleMenuView.updateHandler node_modules/@tiptap/extension-bubble-menu/src/bubble-menu-plugin.ts:200:10
 ❯ BubbleMenuView.update node_modules/@tiptap/extension-bubble-menu/src/bubble-menu-plugin.ts:170:10
 ❯ EditorView.updatePluginViews node_modules/prosemirror-view/dist/index.js:5262:32
 ❯ EditorView.updateStateInner node_modules/prosemirror-view/dist/index.js:5211:14
 ❯ EditorView.updateState node_modules/prosemirror-view/dist/index.js:5142:14
 ❯ Editor.dispatchTransaction node_modules/@tiptap/core/src/Editor.ts:344:15
 ❯ EditorView.dispatch node_modules/prosemirror-view/dist/index.js:5471:33
 ❯ Object.method [as setContent] node_modules/@tiptap/core/src/CommandManager.ts:42:18
 ❯ VueComponent.value src/components/form/tiptap/TiptapEditor.vue:174:1
    172|       // of the input field
    173|       if (val !== this.html) {
    174|         this.editor.commands.setContent(val)
       | ^
    175|       }
    176|     },